/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bagsnack.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bagsnack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1.geometry} material={materials.phong1} />
      <mesh geometry={nodes.polySurface2.geometry} material={materials.FBXASC0493FBXASC032FBXASC045FBXASC032Default} />
    </group>
  )
}

useGLTF.preload('/bagsnack.glb')
