/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gelato.glb 
Author: nicholas.flatt (https://sketchfab.com/nicholas.flatt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gelato-vr-grape-bag-a066e3acfb1340a69941fdc4654e320d
Title: Gelato VR Grape Bag
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/gelato.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Gelato_Grape_Pie_0" position={[-11.248, 4.754, -1.535]} rotation={[0.005, -0.277, 0.011]} scale={[56.947, 44.392, 48.331]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.005']} />
              </group>
              <group name="textured_1" position={[-12.623, 15.705, -2.094]} rotation={[Math.PI / 2, 0, 0.997]} scale={-0.747}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.textured_0} />
              </group>
              <group name="textured001_2" position={[-12.588, 15.692, -2.101]} rotation={[Math.PI / 2, 0, 1.877]} scale={-0.699}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.textured_0} />
              </group>
              <group name="textured002_3" position={[-12.623, 15.705, -2.094]} rotation={[Math.PI / 2, 0, 0.997]} scale={-0.747}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.textured_0} />
              </group>
              <group name="textured003_4" position={[-12.588, 15.692, -2.101]} rotation={[Math.PI / 2, 0, 1.877]} scale={-0.699}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.textured_0} />
              </group>
              <group name="textured004_5" position={[-12.623, 15.705, -2.094]} rotation={[Math.PI / 2, 0, 0.997]} scale={-0.747}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.textured_0} />
              </group>
              <group name="CameraShakifyv2_Camera_0_6" position={[-12308.8, -11100.4, -3524]} />
              <group name="CameraShakifyv2_CAMERA_-_360_Track_0_7" position={[-12308.8, -11100.4, -3524]} />
              <group name="CameraShakifyv2_CAMERA_-_Medium_Pull_0_8" position={[-12308.8, -11100.4, -3524]} />
              <group name="CameraShakifyv2_CAMERA_-_Reverse_Dolly_Shot_0_9" position={[-12308.8, -11100.4, -3524]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gelato.glb')
